"""add tipo_ciclo and criterio_classificacao to ciclo_activities

Revision ID: 2ef7b37e1746
Revises: d2b8bd99be73
Create Date: 2026-06-01 15:49:33.356167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef7b37e1746'
down_revision: Union[str, None] = 'd2b8bd99be73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ciclo_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_ciclo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('criterio_classificacao', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ciclo_activities', schema=None) as batch_op:
        batch_op.drop_column('criterio_classificacao')
        batch_op.drop_column('tipo_ciclo')

    # ### end Alembic commands ###
