"""add comments alertrules alertevents version email

Revision ID: 9ec62e95f1fa
Revises: ab9365c09f46
Create Date: 2026-06-01 17:17:12.824765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec62e95f1fa'
down_revision: Union[str, None] = 'ab9365c09f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_analysis_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('parent_analysis_id')

    # ### end Alembic commands ###
